import { describe, expect, it } from "vitest";
import type { GuideDetail } from "./guide.service";
import { render_guide_html_export } from "./guide-html-export";

const guide_detail: GuideDetail = {
  guide: {
    id: "guide_1",
    organization_id: "organization_1",
    project_id: "project_1",
    source_capture_session_id: "capture_session_1",
    title: "Department <Guide>",
    description: "Use \"safe\" setup & review.",
    status: "draft",
    created_by_id: "org_user_1",
    updated_by_id: "org_user_1",
    version: 1,
    created_at: "2026-06-05T00:00:00.000Z",
    updated_at: "2026-06-05T00:00:00.000Z",
  },
  guide_blocks: [{
    id: "block_step_2",
    organization_id: "organization_1",
    project_id: "project_1",
    guide_id: "guide_1",
    source_capture_session_id: "capture_session_1",
    source_capture_event_id: "event_2",
    source_capture_asset_id: "asset_2",
    selected_capture_asset_id: null,
    screenshot_hidden: false,
    display_capture_asset_id: "asset_2",
    block_type: "step",
    content: {
      annotations: [{
        id: "ann_1",
        type: "highlight",
        x: 0.2,
        y: 0.15,
        width: 0.25,
        height: 0.1,
      }],
    },
    block_index: 2,
    created_by_id: "org_user_1",
    updated_by_id: "org_user_1",
    version: 1,
    created_at: "2026-06-05T00:00:00.000Z",
    updated_at: "2026-06-05T00:00:00.000Z",
    step: {
      id: "step_2",
      organization_id: "organization_1",
      project_id: "project_1",
      guide_id: "guide_1",
      guide_block_id: "block_step_2",
      source_capture_session_id: "capture_session_1",
      source_capture_event_id: "event_2",
      source_capture_asset_id: "asset_2",
      title: "Click \"Add <Department>\"",
      body: "Use the primary action.\nThen confirm.",
      created_by_id: "org_user_1",
      updated_by_id: "org_user_1",
      version: 1,
      created_at: "2026-06-05T00:00:00.000Z",
      updated_at: "2026-06-05T00:00:00.000Z",
    },
  }, {
    id: "block_header_1",
    organization_id: "organization_1",
    project_id: "project_1",
    guide_id: "guide_1",
    source_capture_session_id: null,
    source_capture_event_id: null,
    source_capture_asset_id: null,
    selected_capture_asset_id: null,
    screenshot_hidden: false,
    display_capture_asset_id: null,
    block_type: "header",
    content: { title: "Department fields" },
    block_index: 1,
    created_by_id: "org_user_1",
    updated_by_id: "org_user_1",
    version: 1,
    created_at: "2026-06-05T00:00:00.000Z",
    updated_at: "2026-06-05T00:00:00.000Z",
    step: null,
  }, {
    id: "block_paragraph_3",
    organization_id: "organization_1",
    project_id: "project_1",
    guide_id: "guide_1",
    source_capture_session_id: null,
    source_capture_event_id: null,
    selected_capture_asset_id: null,
    source_capture_asset_id: null,
    screenshot_hidden: false,
    display_capture_asset_id: null,
    block_type: "paragraph",
    content: { body: "Choose the right settings." },
    block_index: 3,
    created_by_id: "org_user_1",
    updated_by_id: "org_user_1",
    version: 1,
    created_at: "2026-06-05T00:00:00.000Z",
    updated_at: "2026-06-05T00:00:00.000Z",
    step: null,
  }, {
    id: "block_tip_4",
    organization_id: "organization_1",
    project_id: "project_1",
    guide_id: "guide_1",
    source_capture_session_id: null,
    source_capture_event_id: null,
    source_capture_asset_id: null,
    selected_capture_asset_id: null,
    screenshot_hidden: false,
    display_capture_asset_id: null,
    block_type: "tip",
    content: { title: "Parent departments", body: "Use groups." },
    block_index: 4,
    created_by_id: "org_user_1",
    updated_by_id: "org_user_1",
    version: 1,
    created_at: "2026-06-05T00:00:00.000Z",
    updated_at: "2026-06-05T00:00:00.000Z",
    step: null,
  }, {
    id: "block_alert_5",
    organization_id: "organization_1",
    project_id: "project_1",
    guide_id: "guide_1",
    source_capture_session_id: null,
    source_capture_event_id: null,
    source_capture_asset_id: null,
    selected_capture_asset_id: null,
    screenshot_hidden: false,
    display_capture_asset_id: null,
    block_type: "alert",
    content: { body: "This changes reports." },
    block_index: 5,
    created_by_id: "org_user_1",
    updated_by_id: "org_user_1",
    version: 1,
    created_at: "2026-06-05T00:00:00.000Z",
    updated_at: "2026-06-05T00:00:00.000Z",
    step: null,
  }, {
    id: "block_divider_6",
    organization_id: "organization_1",
    project_id: "project_1",
    guide_id: "guide_1",
    source_capture_session_id: null,
    source_capture_event_id: null,
    source_capture_asset_id: null,
    selected_capture_asset_id: null,
    screenshot_hidden: false,
    display_capture_asset_id: null,
    block_type: "divider",
    content: null,
    block_index: 6,
    created_by_id: "org_user_1",
    updated_by_id: "org_user_1",
    version: 1,
    created_at: "2026-06-05T00:00:00.000Z",
    updated_at: "2026-06-05T00:00:00.000Z",
    step: null,
  }, {
    id: "block_hidden_7",
    organization_id: "organization_1",
    project_id: "project_1",
    guide_id: "guide_1",
    source_capture_session_id: "capture_session_1",
    source_capture_event_id: "event_7",
    source_capture_asset_id: "asset_hidden",
    selected_capture_asset_id: null,
    screenshot_hidden: true,
    display_capture_asset_id: null,
    block_type: "step",
    content: null,
    block_index: 7,
    created_by_id: "org_user_1",
    updated_by_id: "org_user_1",
    version: 1,
    created_at: "2026-06-05T00:00:00.000Z",
    updated_at: "2026-06-05T00:00:00.000Z",
    step: {
      id: "step_hidden_7",
      organization_id: "organization_1",
      project_id: "project_1",
      guide_id: "guide_1",
      guide_block_id: "block_hidden_7",
      source_capture_session_id: "capture_session_1",
      source_capture_event_id: "event_7",
      source_capture_asset_id: "asset_hidden",
      title: "Hidden screenshot step",
      body: null,
      created_by_id: "org_user_1",
      updated_by_id: "org_user_1",
      version: 1,
      created_at: "2026-06-05T00:00:00.000Z",
      updated_at: "2026-06-05T00:00:00.000Z",
    },
  }],
  source_capture_assets: [{
    id: "asset_2",
    capture_session_id: "capture_session_1",
    asset_type: "screenshot",
    width: 1440,
    height: 900,
    device_pixel_ratio: 1,
    page_url: "https://example.test/departments?filter=<all>",
    page_title: "Department <List>",
    captured_at: "2026-06-05T00:00:00.000Z",
    file_url: "/api/v1/projects/project_1/capture-sessions/capture_session_1/assets/asset_2/file",
    file: {
      id: "file_2",
      original_name: "departments.png",
      mime_type: "image/png",
      size_bytes: 123456,
    },
  }, {
    id: "asset_hidden",
    capture_session_id: "capture_session_1",
    asset_type: "screenshot",
    width: 1440,
    height: 900,
    device_pixel_ratio: 1,
    page_url: null,
    page_title: "Hidden",
    captured_at: "2026-06-05T00:00:00.000Z",
    file_url: "/api/v1/projects/project_1/capture-sessions/capture_session_1/assets/asset_hidden/file",
    file: {
      id: "file_hidden",
      original_name: "hidden.png",
      mime_type: "image/png",
      size_bytes: 123456,
    },
  }],
};

describe("guide HTML export renderer", () => {
  it("renders escaped guide blocks in order with local images and annotations", () => {
    const export_result = render_guide_html_export(guide_detail);

    expect(export_result.image_references).toEqual([{
      capture_asset_id: "asset_2",
      asset_path: "assets/2-asset_2.png",
      mime_type: "image/png",
    }]);
    expect(export_result.html).toContain("<title>Department &lt;Guide&gt;</title>");
    expect(export_result.html).toContain("<h1>Department &lt;Guide&gt;</h1>");
    expect(export_result.html).toContain("Use &quot;safe&quot; setup &amp; review.");
    expect(export_result.html.indexOf("Department fields"))
      .toBeLessThan(export_result.html.indexOf("Click &quot;Add &lt;Department&gt;&quot;"));
    expect(export_result.html).toContain("Choose the right settings.");
    expect(export_result.html).toContain("Tip");
    expect(export_result.html).toContain("Parent departments");
    expect(export_result.html).toContain("Alert");
    expect(export_result.html).toContain("<hr");
    expect(export_result.html).toContain("src=\"assets/2-asset_2.png\"");
    expect(export_result.html).toContain("alt=\"Department &lt;List&gt;\"");
    expect(export_result.html).toContain("left: 20%; top: 15%; width: 25%; height: 10%;");
    expect(export_result.html).not.toContain("/api/v1/projects");
    expect(export_result.html).not.toContain("asset_hidden.png");
    expect(export_result.html).not.toContain("storage_key");
    expect(export_result.html).not.toContain("<Guide>");
    expect(export_result.html).not.toContain("<Department>");
  });
});
